
services:
  app:
    build: .
    ports:
      - "13006:80"
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017/
    volumes:
      - ./app:/app

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
